### ISSUE TITLE
vim ALE support

### ISSUE THREAD

**Issue by SuperSandro2000** [nerdypepper/statix#10]
It would be great if [vim ale](https://github.com/dense-analysis/ale) support could be added.

**Comment by houstdav000** [comment]
I can look into adding it. I've added some tools to ale before, though I'm currently adding statix to [nvim-lint](https://github.com/mfussenegger/nvim-lint).

**Comment by houstdav000** [comment]
So I was thinking it'd be required to have stream support for ALE to support it as I said in #16, but [ALE does support creating a temporary file](https://github.com/dense-analysis/ale/blob/f37cd1fd4fc17173a98649d8a0b2f37ce7ba61cf/autoload/ale/command.vim#L190). It would still be advantageous to have stream support, but until that's implemented, it should still be possible.

**Comment by nerdypepper** [comment]
Oh no worries, I have nearly got the stdin flag ready, thanks again, for picking this up!

**Comment by houstdav000** [comment]
I'm a lot worse with regex than I remember, but I've got <https://github.com/dense-analysis/ale/pull/3967> submitted

**Comment by houstdav000** [comment]
Since #16's implemented, I'll see about adding ALE fixer support next

**Comment by houstdav000** [comment]
I didn't realize until I tried to test it, now that 0.4.0 is implemented, and that uses `stdout` instead of `stderr`, that PR I made is pretty much outdated. I'll also for now have to use a nix shell to test since 0.4.0 hasn't yet hit `nixpkgs-unstable`

**Comment by houstdav000** [comment]
Okay, I've got a full v0.4.0 version at <https://github.com/houstdav000/ale/tree/feature/statix> that implements both `check` and `fix` properly, but since that's not the version in `nixpkgs-unstable`, I'm unsure whether to wait or just make the PR now

**Comment by nerdypepper** [comment]
I'll open a PR with `v0.4.0` later today.

>and that uses stdout instead of stderr

Ah yeah, I decided that diagnostics would go to stdout and errors raised by statix during its run (things like IO errors, CLI errors etc.) would go into stderr. What do you think?

**Comment by houstdav000** [comment]
> Ah yeah, I decided that diagnostics would go to stdout and errors raised by statix during its run (things like IO errors, CLI errors etc.) would go into stderr. What do you think?

It makes sense to me, and works pretty well from what I saw when testing it.

**Comment by houstdav000** [comment]
`nixpkgs-unstable` has v0.4.0, and I made a minor fix for that previous implementation, so it should be good now in https://github.com/dense-analysis/ale/pull/3969

**Comment by houstdav000** [comment]
https://github.com/dense-analysis/ale/pull/3969 has been merged :tada:

**Comment by nerdypepper** [comment]
Thanks @houstdav000 for working on this :partying_face:

**Comment by nerdypepper** [comment]
I'll create a section on the readme with all the editor integrations so far.
