### ISSUE TITLE
Feature request: allow disabling certain checks

### ISSUE THREAD

**Issue by SuperSandro2000** [nerdypepper/statix#19]
I want to start applying the tool to nixpkgs. For that I would like to disable certain checks or only enable one to keep the changes small and for example only remove extra ``()``.

**Comment by nerdypepper** [comment]
Understood. For now, I'll add a config file option, to enable/disable lints. In the future, I think I'll add a way to selectively ignore issues with a comment such as:

```
#statix ignore
("hello")
```

**Comment by SuperSandro2000** [comment]
I think we want to add which issue should be ignored to the comment like shellcheck does.

**Comment by nerdypepper** [comment]
Oh yeah, I intend to support two syntaxes:

```
# skip all issues on next line
#statix ignore

# skip specific issues on next line
#statix ignore: useless_parens, empty_let_in
```

**Comment by nerdypepper** [comment]
With the latest release (v0.4.1), you can disable checks with a configuration file. Please see https://github.com/nerdypepper/statix#configuration. Feel free to reopen or create a new issue if there are bugs with the new flag!
