### ISSUE TITLE
Non-zero exit code on found problems

### ISSUE THREAD

**Issue by NobbZ** [nerdypepper/statix#20]
I checked statix today and except for the unquoted splices (#8) and empty pattern I agree with its suggestions on my projects and I'd like to add it to CI.

Though to make any use of it in CI, it is required that we get a non-zero exit code on found suggestions.

**Comment by nerdypepper** [comment]
>Though to make any use of it in CI, it is required that we get a non-zero exit code on found suggestions.

Understood, will try to work on this over the weekend.

>empty pattern

Feel free to open an issue about this as well. I'd be happy to update the rule if you feel it is noisy.

**Comment by m1-s** [comment]
Any news on this? We also would like to integrate statix into our CI but without proper return codes its useless to us.

**Comment by nerdypepper** [comment]
Sorry, this slipped my radar again, the next release will contain this fix.

**Comment by SuperSandro2000** [comment]
How about adding a -q argument like grep?

**Comment by nerdypepper** [comment]
i have opened #34 to fix this, behavior is as follows:

- exit with 1 if warnings or syntax errors are present
- exit with 0 if no warnings are produced

**Comment by nerdypepper** [comment]
@SuperSandro2000 hmm, is that any different from redirecting all output of statix to `/dev/null`?

**Comment by meain** [comment]
One thing that I think grep does along with just silencing output is to exit immediately as soon a single match is found and not doing the full search.
