### ISSUE TITLE
Ignore multiple files

### ISSUE THREAD

**Issue by NobbZ** [nerdypepper/statix#21]
To get my configuration in an initial acceptable shape, I wanted to use `statix` and `-i` those files that do not need further treatment in my opinion, as I disagree with the remaining rules.

THough `-i` seems to be not repeatable, how to ignore more than one file?

**Comment by nerdypepper** [comment]
The `-i` flag accepts more than one glob, you can run `statix` like so:

`statix check target_dir -i Cargo.nix '*abc.nix' 'some_other_file.nix'`
