### ISSUE TITLE
Support brew and/or cargo

### ISSUE THREAD

**Issue by delneg** [nerdypepper/statix#24]
Hello, is it possible to get this tool to crates.io and/or homebrew ?
That would streamline the installation process greatly (because if I don't use nix on a mac, I have to build it from source). Thanks in advance!

**Comment by SuperSandro2000** [comment]
You should be able to clone the source and do ``cargo build``.

**Comment by delneg** [comment]
That's what I've been referring to as 'build from source', that's nor easy (I've to have rust / cargo installed & configured) nor is it user-friendly

**Comment by nerdypepper** [comment]
If I understand, you are looking for a pre-built binary of sorts? I think crates.io does not support such a thing (installing from crates.io with `cargo install statix` would still build from scratch). I am not familiar with homebrew/taps, but that should be doable.

I haven't really thought about supporting other package managers, but if you'd like, I can help get a darwin output for `statix` on nixpkgs.

**Comment by delneg** [comment]
Yep, you understood correctly.
It would be nice to at least do `cargo install statix` and not git clone -> build -> link.
Regarding homebrew - here's some guides I managed to find:

step by step one
https://betterprogramming.pub/a-step-by-step-guide-to-create-homebrew-taps-from-github-repos-f33d3755ba74
official
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

So, all in all it requires creating a ruby 'description file' in a separate repo, specifying the deps & release tag and that should be it.
I'll probably be able to help testing it also

**Comment by chenrui333** [comment]
I just filed a PR to include this tool into homebrew-core registry, feel free to comment on that PR. Thanks!
https://github.com/Homebrew/homebrew-core/pull/91030

**Comment by nerdypepper** [comment]
That is amazing @chenrui333, much appreciated!

**Comment by nerdypepper** [comment]
> It would be nice to at least do cargo install statix and not git clone -> build -> link.

@delneg you can do  `cargo install --git https://github.com/nerdypepper/statix` and skip through the cloning/linking bits.

**Comment by delneg** [comment]
> > It would be nice to at least do cargo install statix and not git clone -> build -> link.
> 
> @delneg you can do `cargo install --git https://github.com/nerdypepper/statix` and skip through the cloning/linking bits.

Thanks, didn't know that it's possible with cargo.
Probably a good idea to include that into README together with brew instruction when the PR gets merged

**Comment by chenrui333** [comment]
Now the homebrew-core PR has been installed, add a PR to include docs for install with brew

**Comment by nerdypepper** [comment]
Thanks for working on this @chenrui333!

**Comment by chenrui333** [comment]
my pleasure :)
