### ISSUE TITLE
statix also checks git ref files of branches with ".nix" suffix

### ISSUE THREAD

**Issue by tfc** [nerdypepper/statix#28]
i happen to have files like this in my project:

- `.git/logs/refs/heads/foobar.nix`
- `.git/logs/refs/remotes/remote-name/foobar.nix`

statix will scan them unless explicitly ignored and error-out because these files have nothing to do with nix, it's just branch names with a .nix suffix.

i can tell statix to ignore them using `--ignore .git` but it appears useful to teach statix to generally avoid .git subfolders, does this make sense?

**Comment by nerdypepper** [comment]
The fix is on master, I'll make a release tomorrow (with a bunch of other cool changes ;). It should land in nixpkgs-unstable in a couple of days.

**Comment by nerdypepper** [comment]
Fixed in `v0.5.0`, thanks for the report!
