### ISSUE TITLE
[Bug] Empty Pattern in `nixosModule`

### ISSUE THREAD

**Issue by maydayv7** [nerdypepper/statix#31]
Original File:
```nix
{ ... }: rec { imports = [ ./console.nix ./firmware.nix ]; }
```

Lint:
```shellsession
$ statix check
[W10] Warning: Found empty pattern in function argument
   ╭─[./modules/base/default.nix:1:1]
   │
 1 │ { ... }: rec { imports = [ ./console.nix ./firmware.nix ]; }
   · ───┬───  
   ·    ╰───── This pattern is empty, use _ instead
───╯
```

File after using `statix fix`:
```nix
_: rec { imports = [ ./console.nix ./firmware.nix ]; }
```

Error:
```shellsession
$ nix flake check
error: module must match an open attribute set ('{ config, ... }')
 … while checking the NixOS module 'nixosModules.base'
```

Using `statix 0.4.0` on `NixOS 21.11` with `Nix 2.5`

**Comment by maydayv7** [comment]
Just got to know that `imports` is smart enough to handle removing all parameters in a module, so closing this issue

**Comment by nerdypepper** [comment]
The suggestion by statix for modules should probably be `{ }:` and not `_:`. I do think this is still a valid bug.

**Comment by maydayv7** [comment]
> The suggestion by statix for modules should probably be `{ }:` and not `_:`. I do think this is still a valid bug.

Actually even `{ }:` instead of `{ ... }:` produces an error
`anonymous function called with unexpected argument`

**Comment by nerdypepper** [comment]
Understood, in that case not raising this issue on modules is the best idea.

**Comment by nerdypepper** [comment]
Should be fixed on latest master, thanks for the report!
