### ISSUE TITLE
statix stops linting when seeing an empty-ish directory

### ISSUE THREAD

**Issue by tljuniper** [nerdypepper/statix#38]
When doing some source filtering, I came across some weird behavior. When checking a directory with `statix check <dir>`, statix aborts when coming across a directory that has either no files in it or only other directories:

```
$ tree
.
└── dir
    └── broken.nix

1 directory, 1 file
```

Once you create any file in `.`, statix will continue checking the files:

```
# Go into empty directory `.`
$ mkdir dir
$ echo "{}: 42" > dir/broken.nix

$ statix check .
$ touch README.md
$ statix check .
[W10] Warning: Found empty pattern in function argument
   ╭─[./dir/broken.nix:1:1]
   │
 1 │ {}: 42
   · ─┬  
   ·  ╰── This pattern is empty, use _ instead
───╯
```

I can't read Rust, so I've no idea what causes the issue. Can you help out?

**Comment by nerdypepper** [comment]
Ah, I think I see this issue, let me try to get this fixed over the weekend!
