### ISSUE TITLE
Make include/exclude patterns available in `config.toml`

### ISSUE THREAD

**Issue by NobbZ** [nerdypepper/statix#40]
Currently it seems as if enabling/disabling individual checks/lints is the only thing supported in the `config.toml`, this means that I still have to manually maintain a list of ignored files when running `statix`.

I'd like if this was configurable through the `config.toml`.

**Comment by nerdypepper** [comment]
I have had the same gripe, will add this!

**Comment by nerdypepper** [comment]
implemented in v0.5.5, try `statix dump` for a sample config!
