### ISSUE TITLE
Deletes comments within empty let in

### ISSUE THREAD

**Issue by SuperSandro2000** [nerdypepper/statix#43]
While debugging a package in nixpkgs I noticed the following oddity:
when you format a file which has only comments in the let in, all comments get deleted. Since the comments can be actual code I don't think that is intended.

Before:
```nix
_:

let
# those = {};
# are  = {};
# comments = {};
in {}
``` 
after:
```nix
_:

{}
``` 

statix 0.5.4

**Comment by nerdypepper** [comment]
i think the preferred behavior would be to not raise the lint if comments are present?

**Comment by SuperSandro2000** [comment]
It should probably raise that still since the let in is unused but this is probably not auto fixable or should move the comment outside the let in.

**Comment by nerdypepper** [comment]
understood, just pushed v0.5.6 for this issue. the behaviour is as follows:

- no comment present: lint is raised, fix is applied
- comments only present: lint is raised, fix is not applied

currently there is no way for the user to accept/reject fixes interactively, but ideally, that would be nice for this case.
