### ISSUE TITLE
Can't read statix.toml from nix store

### ISSUE THREAD

**Issue by ursi** [nerdypepper/statix#51]
I tried adding the following as a check for my flake
```
 ${statix}/bin/statix check --config ${./statix.toml} ${./.}
```
and the config was being ignored. I'm having to do this instead
```
ln -s ${./statix.toml} statix.toml
${statix}/bin/statix check ${./.}
```

**Comment by whentze** [comment]
Can we get a tagged release with the fix for this? Nixpkgs (inlcuding unstable) is still shipping statix 0.5.6 where this issue exists.
