### ISSUE TITLE
[bin/src/config.rs:79] [self.ignore.as_slice(), extra_ignores].concat() = []

### ISSUE THREAD

**Issue by neunenak** [nerdypepper/statix#59]
If I run `statix check` on a file or directory, it prints the output:

```[bin/src/config.rs:79] [self.ignore.as_slice(), extra_ignores].concat() = []```

and nothing else. Looking at that line of code, I can see it is using the `dbg!` macro to print some debug output that doesn't seem relevant to the end user.

It looks like this might be the expected output if there are no problems with a particular nix file, but it would be nice if there was some explicit acknowledgement that there was nothing wrong with the linted files, rather than just this debug print and exiting.

**Comment by quasigod-io** [comment]
Also having this issue using 0.5.6

**Comment by samhh** [comment]
For anyone else landing here, this is still present in 0.5.6 in nixpkgs as there hasn't been a release since this was fixed.

**Comment by nerdypepper** [comment]
pushed a tag for 0.5.7 now, should be fixed :crossed_fingers:

**Comment by samhh** [comment]
FYI `--version` still says 0.5.6, probably sourced from here: https://github.com/nerdypepper/statix/blob/master/bin/Cargo.toml#L3

**Comment by nerdypepper** [comment]
nice find, i had this documented in `docs/release.txt`, and i still forgot haha. i dont want to delete the tag, i assum that raises issues for package maintainers, will release v0.5.8.
