### ISSUE TITLE
[Question] Why are unquoted splices an anti-pattern?

### ISSUE THREAD

**Issue by Gerschtli** [nerdypepper/statix#8]
Very cool project! I tried it out and wondered why are unquoted splices an anti-pattern?

Thank you very much :)

**Comment by figsoda** [comment]
Is it possible to disable? I also find this not very useful

**Comment by figsoda** [comment]
There was actually a pr in nixpkgs that removed quotes this: https://github.com/NixOS/nixpkgs/pull/68339 (that was not the only thing that pr did)

**Comment by nerdypepper** [comment]
Hmm interesting, I did see a couple of PRs that _added_ quotes. It looks like adding quotes to unquoted splices was also on the [nix-linter](https://github.com/Synthetica9/nix-linter) roadmap as well:

>Check for unquoted splices, e.g. `foo = bar.${baz};`, since leaving off quotes is just horrible ;)

Anyhow, if folks generally dislike this lint, I think it would be better as opt-in. There is no way to disable lints right now, a configuration file or similar is definitely on the roadmap.

As a side, do you think it would be worth adding a lint that _removes_ quotes from splices that don't require it?

**Comment by figsoda** [comment]
I think that's a good idea. Maybe a configuration option like
```typescript
string-interpolation-quotation = "quoted" | "unquoted" | "unchanged"
```

**Comment by nerdypepper** [comment]
This lint has been removed on `master`, changes will be reflected in the next release. The fix suggested by this lint breaks a bunch of valid nix 2.4 syntax.

**Comment by nerdypepper** [comment]
This lint has been removed altogether.
